steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_IMAGE_NAME'
      - '-f'
      - 'apps/api/Dockerfile'
      - './apps/api'

images:
  - '$_IMAGE_NAME'
